### ISSUE TITLE
Broken dependency on `mw`

### ISSUE THREAD

**Issue by halfak** [wikimedia/articlequality#15]
```
File "./wikiclass/extractors/extractor.py", line 15, in <module>
from mw.lib import reverts
ImportError: No module named 'mw'
```

**Comment by he7d3r** [comment]
This is no longer relevant, as it was removed in https://github.com/wikimedia/articlequality/commit/380e1eaa15ac116ec0cbb22effb36ebc2eaa60b3#diff-01c9ee34cb9cc2d79983c5127fb10abaL15
